import type { Metadata } from 'next';
import Link from 'next/link';
import Footer from '../components/Footer';

export const metadata: Metadata = {
  title: 'Terms of Service — ScoreMyPrompt',
  description: 'Terms and conditions for using the ScoreMyPrompt AI prompt grading service.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <main className="flex-1 max-w-3xl mx-auto px-4 py-16 sm:px-6 lg:px-8">
        <Link href="/" className="text-primary hover:underline text-sm">&larr; Back to ScoreMyPrompt</Link>

        <h1 className="text-3xl font-bold mt-6 mb-2">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-10">Last updated: February 24, 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-8">
          {/* 1 */}
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance</h2>
            <p className="text-gray-300 leading-relaxed">
              By using ScoreMyPrompt (&quot;the Service&quot;), you agree to these Terms of Service. If you do not agree, please do not use the Service.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-xl font-semibold mb-3">2. Service Description</h2>
            <p className="text-gray-300 leading-relaxed">
              ScoreMyPrompt is an AI-powered tool that evaluates the quality of text prompts across six dimensions
              (Precision, Role, Output Format, Mission Context, Structure, Tailoring) and provides a score and feedback.
              The Service is provided &quot;as is&quot; for educational and productivity purposes.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-xl font-semibold mb-3">3. User Tiers</h2>
            <ul className="list-disc list-inside text-gray-300 space-y-1">
              <li><strong>Guest:</strong> Up to 3 free grades per day. No account required.</li>
              <li><strong>Free:</strong> Up to 10 grades per day. Requires a free account.</li>
              <li><strong>Pro ($9.99/month):</strong> Unlimited grades, bulk analysis, CSV export, and priority queue.</li>
            </ul>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-xl font-semibold mb-3">4. Acceptable Use</h2>
            <p className="text-gray-300 leading-relaxed">You agree not to:</p>
            <ul className="list-disc list-inside text-gray-300 space-y-1 mt-2">
              <li>Use the Service for illegal activities or to generate harmful content</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the grading API</li>
              <li>Circumvent usage limits through automated tools or multiple accounts</li>
              <li>Submit prompts containing personally identifiable information of others</li>
              <li>Misrepresent scores or grades for commercial fraud</li>
            </ul>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-xl font-semibold mb-3">5. Intellectual Property</h2>
            <p className="text-gray-300 leading-relaxed">
              The PROMPT scoring framework, website design, and content are owned by ScoreMyPrompt.
              Your prompts remain your property &mdash; we do not claim ownership of content you submit.
              As described in our <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>,
              submitted prompt text is not stored after grading.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-xl font-semibold mb-3">6. Payments & Refunds</h2>
            <p className="text-gray-300 leading-relaxed">
              Pro subscriptions are billed monthly through Stripe. You may cancel at any time from your account dashboard.
              Cancellation takes effect at the end of the current billing period. We offer a 7-day free trial for new Pro subscribers.
              Refunds are handled on a case-by-case basis &mdash; contact us within 14 days of charge.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-xl font-semibold mb-3">7. Disclaimer</h2>
            <p className="text-gray-300 leading-relaxed">
              Scores and feedback are generated by AI and are intended as educational guidance, not definitive assessments.
              ScoreMyPrompt does not guarantee any specific outcome from using the Service.
              We are not responsible for decisions made based on scores or feedback.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
            <p className="text-gray-300 leading-relaxed">
              To the maximum extent permitted by law, ScoreMyPrompt shall not be liable for any indirect, incidental,
              or consequential damages arising from your use of the Service. Our total liability shall not exceed the
              amount you paid to us in the 12 months preceding the claim.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-xl font-semibold mb-3">9. Changes</h2>
            <p className="text-gray-300 leading-relaxed">
              We may update these Terms from time to time. Material changes will be communicated via the website or email.
              Continued use after changes constitutes acceptance.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-xl font-semibold mb-3">10. Contact</h2>
            <p className="text-gray-300 leading-relaxed">
              Questions? Reach us at{' '}
              <a href="mailto:hello@scoremyprompt.com" className="text-primary hover:underline">hello@scoremyprompt.com</a>
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
