import { z } from 'zod';
import crypto from 'crypto';
import * as Sentry from '@sentry/nextjs';
import { getSupabaseAdmin } from '@/app/lib/supabase';
import { BUILDER_SYSTEM_PROMPT } from '@/app/constants/builder-system-prompt';
import { AppError, errorResponse, badRequestResponse, unauthorizedResponse } from '@/app/lib/errors';
import { logger } from '@/app/lib/logger';
import { rateLimit, LIMITS } from '@/app/lib/rate-limit';
import { maskApiKeys } from '@/app/lib/api-key-mask';
import { validateBuilderFiles } from '@/app/lib/builder-validate';
import { getQuota, incrementBuilds, quotaToResponse } from '@/app/lib/builder-quota';
import {
  BuilderAnswersSchema,
  BuilderClaudeOutputSchema,
  type BuilderAnswers,
  type BuilderClaudeOutput,
  type BuilderFileMap,
  type BuilderGenerateResponse,
} from '@/app/types/builder';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const ANTHROPIC_MODEL = 'claude-haiku-4-5-20251001';
const ANTHROPIC_URL = 'https://api.anthropic.com/v1/messages';
const ANTHROPIC_TIMEOUT_MS = 30_000;

interface ResolvedUser {
  id: string;
  tier: 'free' | 'pro';
}

/**
 * Extract user from Authorization: Bearer <token>. In tests, honor
 * x-mock-user-id header so we don't need a live Supabase session.
 */
async function resolveUser(req: Request): Promise<ResolvedUser | null> {
  if (process.env.NODE_ENV === 'test') {
    const mockId = req.headers.get('x-mock-user-id');
    if (!mockId) return null;
    const mockTier = (req.headers.get('x-mock-tier') as 'pro' | 'free') ?? 'free';
    return { id: mockId, tier: mockTier };
  }

  const authHeader = req.headers.get('authorization');
  if (!authHeader || !authHeader.startsWith('Bearer ')) return null;
  const token = authHeader.substring(7);

  const supa = getSupabaseAdmin();
  if (!supa) return null;

  const { data: { user }, error } = await supa.auth.getUser(token);
  if (error || !user) return null;

  // Check Pro tier from user_profiles (PK `id` references auth.users.id, column is `tier`).
  const { data: profile } = await supa
    .from('user_profiles')
    .select('tier')
    .eq('id', user.id)
    .maybeSingle();
  const tier: 'free' | 'pro' = profile?.tier === 'pro' ? 'pro' : 'free';
  return { id: user.id, tier };
}

function mockFileMap(answers: BuilderAnswers): BuilderFileMap {
  // Deterministic mock that passes structural validation (all files ≥ 50 chars).
  const pad = (txt: string) => txt + '\n' + 'x'.repeat(80);
  return {
    'CLAUDE.md': pad(`# ${answers.role} Harness (mock, lang=${answers.lang})

## Project Overview
Generated for role=${answers.role} with tone=${answers.tone}.

## Folder Map
- /context
- /agents
- /templates

## Routing Rules
1. If goal is weekly_research, call research_agent first.
2. If research_agent returns <3 sources, loop before content_agent.

## Work Rules
- Tone: ${answers.tone}
- Automation: ${answers.automation}
- Tools: ${answers.tools.join(', ') || 'none'}`),
    '/context/brand_guidelines.md': pad(`# Brand Voice — ${answers.tone}\nMock guidelines for a ${answers.tone} tone with example phrasing.`),
    '/context/business_context.md': pad(`# Business Context\nRole: ${answers.role}. Goals: ${answers.goals.join(', ')}.`),
    '/agents/research_agent.md': pad('# Research Agent\nMock role: gather credible sources for the selected goals.'),
    '/agents/content_agent.md': pad('# Content Agent\nMock role: draft output aligned with brand guidelines.'),
    '/agents/review_agent.md': pad('# Review Agent\nMock role: fact-check and brand-compliance review.'),
    '/templates/report_template.md': pad('# Report Template\n## {{date}}\n## {{topic}}\n### Findings\n### Sources'),
    '/data/README.md': pad('# /data\nDrop CSVs here with role-appropriate schemas.'),
    '.env.example': pad('ANTHROPIC_API_KEY=sk-your-key-here\nNOTION_API_KEY=secret_your-key-here'),
    'README.md': pad('# My Mock Harness\nGenerated by ScoreMyPrompt in mock mode for testing.'),
    'QUICKSTART.md': pad('# Quickstart\n1. Install VS Code.\n2. Open folder.\n3. Run Claude Code.'),
  };
}

async function callAnthropic(answers: BuilderAnswers, apiKey: string): Promise<BuilderClaudeOutput> {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), ANTHROPIC_TIMEOUT_MS);
  try {
    const res = await fetch(ANTHROPIC_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      signal: ctrl.signal,
      body: JSON.stringify({
        model: ANTHROPIC_MODEL,
        max_tokens: 8000,
        system: BUILDER_SYSTEM_PROMPT,
        messages: [{ role: 'user', content: JSON.stringify(answers) }],
      }),
    });
    if (!res.ok) {
      const text = await res.text();
      throw new AppError(`Anthropic ${res.status}: ${text.slice(0, 200)}`, 'ANTHROPIC_ERROR', 502);
    }
    const json = (await res.json()) as { content?: { text?: string }[] };
    const raw = (json.content?.[0]?.text ?? '').replace(/^```json\s*|```\s*$/g, '').trim();
    return BuilderClaudeOutputSchema.parse(JSON.parse(raw));
  } finally {
    clearTimeout(t);
  }
}

export async function POST(req: Request): Promise<Response> {
  // 1. Rate limit
  const rl = rateLimit(req, LIMITS.ANALYZE);
  if (!rl.ok) return rl.response;

  // 2. Auth
  const user = await resolveUser(req);
  if (!user) return unauthorizedResponse('Sign in required to use Builder');

  // 3. Parse & validate body
  let answers: BuilderAnswers | undefined;
  try {
    const body = await req.json();
    // Mask any API keys that might sneak into user-provided strings.
    const sanitized = body && typeof body === 'object' ? JSON.parse(maskApiKeys(JSON.stringify(body))) : body;
    answers = BuilderAnswersSchema.parse(sanitized);
  } catch (err) {
    if (err instanceof z.ZodError) return badRequestResponse('Invalid request', err.issues);
    return badRequestResponse('Invalid JSON body');
  }

  try {
    // 4. Quota check
    const quotaState = await getQuota(user.id, user.tier);
    if (!quotaState.canBuild) {
      return Response.json(
        {
          error: 'Monthly build quota exhausted',
          code: 'QUOTA_EXHAUSTED',
          quota: quotaToResponse(quotaState),
        },
        { status: 402, headers: rl.response.headers },
      );
    }

    // 5. Generate file map (Claude call or mock)
    const apiKey = process.env.ANTHROPIC_API_KEY;
    let files: BuilderFileMap;
    if (!apiKey) {
      files = mockFileMap(answers);
    } else {
      try {
        const out = await callAnthropic(answers, apiKey);
        files = out.files;
      } catch (err) {
        logger.warn('Anthropic builder call failed, retrying once', { error: String(err) });
        try {
          const out = await callAnthropic(answers, apiKey);
          files = out.files;
        } catch (err2) {
          logger.warn('Anthropic builder retry failed, falling back to mock', { error: String(err2) });
          files = mockFileMap(answers);
        }
      }
    }

    // 6. Validate structural shape
    const validation = validateBuilderFiles(files);
    if (!validation.ok) {
      throw new AppError(
        `Generated file map failed validation: ${validation.reason}`,
        'INVALID_GENERATION',
        502,
      );
    }

    // 7. Persist
    const supa = getSupabaseAdmin();
    let id: string = crypto.randomUUID();
    const expiresAt = new Date(Date.now() + 5 * 60 * 1000).toISOString();
    const isProBuild = user.tier === 'pro';

    if (supa) {
      const { data, error } = await supa
        .from('builder_outputs')
        .insert({
          user_id: user.id,
          answers,
          files,
          is_pro_build: isProBuild,
          expires_at: expiresAt,
        })
        .select('id')
        .single();
      if (error) {
        logger.warn('builder_outputs insert failed', { error: error.message });
      } else if (data) {
        id = data.id as string;
      }
    } else {
      logger.warn('Supabase not configured — build result will not persist');
    }

    // 8. Increment quota
    await incrementBuilds(user.id, id);

    // 9. Refresh quota for response
    const finalQuota = await getQuota(user.id, user.tier);

    const response: BuilderGenerateResponse = {
      id,
      files,
      expiresAt,
      isProBuild,
      quota: {
        buildsUsed: finalQuota.buildsUsed,
        bonusFromShare: finalQuota.bonusFromShare,
        limit: finalQuota.limit,
      },
    };
    return Response.json(response, { headers: rl.response.headers });
  } catch (err) {
    Sentry.withScope((scope) => {
      scope.setTag('route', 'builder_generate');
      if (answers) scope.setTag('role', answers.role);
      Sentry.captureException(err);
    });
    if (err instanceof AppError) return errorResponse(err);
    logger.error('Unhandled builder generate error', { error: String(err) });
    return errorResponse(err as Error);
  }
}
