/**
 * AQ 테스트 문제 뱅크
 * 영역: tool(도구 활용), ethics(윤리/편향), concept(개념 이해)
 * 프롬프트 영역은 기존 SMP 엔진 활용
 */
import type { AQQuestion } from './types';

// ─── 도구 활용 (Tool) ────────────────────────────
export const TOOL_QUESTIONS: AQQuestion[] = [
  {
    id: 'tool-1',
    domain: 'tool',
    type: 'scenario',
    difficulty: 1,
    question: '마케팅 팀에서 다음 분기 캠페인 이미지를 만들어야 합니다. 가장 적합한 AI 도구 조합은?',
    scenario: '예산은 제한적이고, 브랜드 가이드라인에 맞는 고품질 이미지 20장이 필요합니다.',
    options: [
      { text: 'Midjourney로 초안 생성 → Canva AI로 브랜드 가이드라인 적용 → 팀 리뷰', score: 10 },
      { text: 'ChatGPT에게 이미지 설명을 작성하게 한 후 직접 디자인', score: 4 },
      { text: 'DALL-E로 20장을 한 번에 생성하여 바로 사용', score: 3 },
      { text: '구글에서 무료 이미지를 검색하여 AI로 편집', score: 2 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '복잡한 크리에이티브 작업은 생성 AI + 편집 도구를 조합하고, 사람의 리뷰를 거치는 것이 최적입니다.',
  },
  {
    id: 'tool-2',
    domain: 'tool',
    type: 'multiple_choice',
    difficulty: 1,
    question: '100페이지 PDF 보고서의 핵심 내용을 빠르게 파악하려면 어떤 접근이 가장 효과적인가요?',
    options: [
      { text: 'Claude/ChatGPT에 PDF를 업로드하여 요약 요청', score: 10 },
      { text: '보고서 전체를 ChatGPT에 복사-붙여넣기', score: 4 },
      { text: 'AI에게 "보고서 요약해줘"라고만 말하기 (파일 없이)', score: 1 },
      { text: '직접 읽으면서 메모하기', score: 3 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '대용량 문서 분석에는 파일 업로드를 지원하는 AI 도구를 활용하는 것이 가장 효율적입니다.',
  },
  {
    id: 'tool-3',
    domain: 'tool',
    type: 'scenario',
    difficulty: 2,
    question: '다국어 고객 지원 챗봇을 구축해야 합니다. 어떤 전략이 가장 효과적인가요?',
    scenario: '한국어, 영어, 일본어 지원이 필요하고, 회사 제품 FAQ 300개가 있습니다.',
    options: [
      { text: 'RAG(검색 증강 생성) 기반 챗봇 — FAQ를 벡터 DB에 저장, GPT-4로 응답 생성', score: 10 },
      { text: 'ChatGPT API에 모든 FAQ를 시스템 프롬프트로 넣기', score: 4 },
      { text: '각 언어별로 별도 룰 기반 챗봇 3개 개발', score: 3 },
      { text: 'Google Translate API로 한국어 챗봇의 응답을 번역', score: 5 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'RAG 아키텍처는 대량 지식을 효율적으로 활용하면서도 자연스러운 다국어 응답을 생성할 수 있습니다.',
  },
  {
    id: 'tool-4',
    domain: 'tool',
    type: 'multiple_choice',
    difficulty: 2,
    question: '다음 중 "멀티모달 AI 활용"의 올바른 예시는?',
    options: [
      { text: '사진을 GPT-4 Vision에 올려서 텍스트 설명을 받고, 그걸 바탕으로 코드 생성', score: 10 },
      { text: 'ChatGPT에서 긴 대화를 이어가기', score: 1 },
      { text: '여러 AI 서비스에 같은 질문을 동시에 하기', score: 2 },
      { text: 'AI가 생성한 이미지를 다운로드하기', score: 3 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '멀티모달은 텍스트·이미지·음성 등 여러 형태의 데이터를 함께 처리하는 것을 의미합니다.',
  },
  {
    id: 'tool-5',
    domain: 'tool',
    type: 'scenario',
    difficulty: 3,
    question: '스타트업에서 AI를 활용한 데이터 분석 파이프라인을 설계해야 합니다. 가장 현실적인 접근은?',
    scenario: '월 1만 건의 고객 피드백을 분류·분석해야 하고, 개발 인력은 1명입니다.',
    options: [
      { text: 'OpenAI API로 감성 분석 + 자동 태깅 → 결과를 대시보드(Notion/Sheets)에 자동 적재', score: 10 },
      { text: '직접 ML 모델을 학습시켜 감성 분류기 구축', score: 3 },
      { text: 'ChatGPT 웹에서 매일 수동으로 분석', score: 2 },
      { text: 'AI 없이 키워드 기반 룰로 분류', score: 4 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '소규모 팀에서는 API 기반 자동화가 가장 현실적이고 확장 가능한 접근입니다.',
  },
  {
    id: 'tool-6',
    domain: 'tool',
    type: 'multiple_choice',
    difficulty: 1,
    question: '회의 1시간 녹음 파일에서 액션 아이템과 결정사항을 빠르게 뽑아내려면?',
    options: [
      { text: 'Whisper 등 음성 인식으로 텍스트 변환 → LLM에 "회의록·액션·결정사항" 요청', score: 10 },
      { text: '녹음을 처음부터 끝까지 들으며 직접 메모', score: 3 },
      { text: '녹음 파일을 ChatGPT 텍스트 입력란에 붙여넣기', score: 1 },
      { text: '회의 참가자에게 각자 기억나는 액션 아이템을 물어봄', score: 4 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '음성→텍스트→LLM 요약은 회의록 자동화의 표준 워크플로우입니다. 녹음 파일은 LLM이 직접 못 읽습니다.',
  },
  {
    id: 'tool-7',
    domain: 'tool',
    type: 'scenario',
    difficulty: 2,
    question: '반복적인 인보이스 처리(이메일 → PDF 추출 → ERP 입력)를 AI로 자동화하려 합니다. 가장 효과적인 구성은?',
    scenario: '매일 50건의 PDF 인보이스가 이메일로 도착하고, 사람이 ERP에 수동 입력 중입니다.',
    options: [
      { text: 'n8n/Make 워크플로우 + 비전 LLM으로 PDF에서 항목 추출 → ERP API 호출', score: 10 },
      { text: '한 명을 ChatGPT 사용에 익숙하게 훈련시켜 반자동화', score: 4 },
      { text: 'PDF를 OCR한 텍스트만 ChatGPT에 매번 붙여넣고 결과를 복사', score: 5 },
      { text: '인력을 한 명 더 채용', score: 1 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '워크플로우 도구(n8n/Make/Zapier) + LLM의 조합이 반복 업무 자동화의 정석입니다.',
  },
  {
    id: 'tool-8',
    domain: 'tool',
    type: 'multiple_choice',
    difficulty: 2,
    question: '복잡한 추론이 필요한 분석에는 어떤 모델을 선택하는 것이 가장 적절한가요?',
    options: [
      { text: 'reasoning(추론) 모델 — 시간이 더 걸리지만 단계적 사고로 정확도가 높음', score: 10 },
      { text: '항상 가장 비싼 모델', score: 4 },
      { text: '항상 가장 빠른 경량 모델', score: 2 },
      { text: '여러 모델에 같은 질문을 하고 다수결 채택', score: 6 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '추론 모델은 step-by-step 사고를 거쳐 복잡한 문제에서 정확도가 높습니다. 작업 성격에 맞춰 모델을 선택하는 것이 비용·품질의 균형점입니다.',
  },
  {
    id: 'tool-9',
    domain: 'tool',
    type: 'scenario',
    difficulty: 3,
    question: '"AI 에이전트"로 매일 아침 경쟁사 가격 변동을 자동 모니터링하려 합니다. 가장 안정적인 설계는?',
    scenario: '경쟁사 5곳의 핵심 상품 가격을 매일 확인하여 변동 시 슬랙으로 알림이 필요합니다.',
    options: [
      { text: '에이전트 = 스케줄러 + 명확한 도구(웹 스크래핑/검색) + 종료 조건 + 사람 승인 게이트', score: 10 },
      { text: '"매일 경쟁사 가격 확인하고 알려줘"라고 챗봇에 한 번 말해 둠', score: 1 },
      { text: '에이전트가 인터넷을 자유롭게 돌아다니며 정보 수집', score: 3 },
      { text: '매일 사람이 각 사이트를 직접 확인해서 입력', score: 2 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '에이전트는 자유도가 높을수록 비용·실패율이 폭증합니다. 도구·종료조건·승인 게이트로 자유도를 좁히는 것이 운영 핵심입니다.',
  },
  {
    id: 'tool-10',
    domain: 'tool',
    type: 'multiple_choice',
    difficulty: 2,
    question: '한국어 콘텐츠를 다루는 작업에서 가장 합리적인 접근은?',
    options: [
      { text: '용도별로 모델을 비교 선택 — 한국어 특화 모델(클로바 X, Wrtn 등)과 글로벌 모델을 작업별로', score: 10 },
      { text: '무조건 글로벌 최신 모델 하나만 사용', score: 5 },
      { text: '무조건 국내 모델만 사용', score: 4 },
      { text: '한국어→영어 번역 후 영어로 처리하고 다시 번역', score: 3 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '한국어 자연스러움·비용·맥락 이해에 따라 모델 선택이 달라집니다. 작업별 적합성이 핵심.',
  },
];

// ─── 윤리/편향 (Ethics) ──────────────────────────
export const ETHICS_QUESTIONS: AQQuestion[] = [
  {
    id: 'ethics-1',
    domain: 'ethics',
    type: 'scenario',
    difficulty: 1,
    question: 'AI가 생성한 글을 회사 블로그에 게시하려 합니다. 가장 적절한 대응은?',
    scenario: 'AI가 작성한 초안이 매우 잘 쓰여져 있어 수정이 거의 필요 없습니다.',
    options: [
      { text: '팩트체크 후 게시하되, AI 활용 사실을 명시하거나 사내 정책에 따름', score: 10 },
      { text: '그대로 게시 — AI가 잘 썼으니 문제없음', score: 2 },
      { text: 'AI가 쓴 부분을 전부 삭제하고 직접 다시 작성', score: 4 },
      { text: '저자를 "AI"로 표기하고 게시', score: 6 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'AI 생성 콘텐츠는 반드시 사실 확인이 필요하고, 투명성 정책에 따라 공개하는 것이 바람직합니다.',
  },
  {
    id: 'ethics-2',
    domain: 'ethics',
    type: 'multiple_choice',
    difficulty: 1,
    question: 'AI 채용 시스템이 특정 성별을 불리하게 평가한다는 보고가 있습니다. 원인으로 가장 가능성이 높은 것은?',
    options: [
      { text: '학습 데이터에 과거의 성별 편향이 반영되어 있기 때문', score: 10 },
      { text: 'AI가 의도적으로 차별하도록 프로그래밍되었기 때문', score: 1 },
      { text: 'AI의 처리 속도가 느려서 발생하는 오류', score: 0 },
      { text: '특정 성별의 지원자가 더 적기 때문', score: 4 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'AI 편향의 주요 원인은 학습 데이터에 내재된 과거의 사회적 편향입니다.',
  },
  {
    id: 'ethics-3',
    domain: 'ethics',
    type: 'scenario',
    difficulty: 2,
    question: 'AI로 고객 데이터를 분석하려는데, 개인정보 보호 관점에서 가장 적절한 접근은?',
    scenario: '고객 이름, 이메일, 구매 이력이 포함된 10만 건의 데이터를 외부 AI API로 분석하려 합니다.',
    options: [
      { text: '개인 식별 정보를 익명화/가명화한 후 AI에 전송', score: 10 },
      { text: '고객에게 동의를 받았으니 그대로 전송', score: 4 },
      { text: 'AI가 데이터를 저장하지 않는다고 하니 그대로 전송', score: 2 },
      { text: 'AI 분석을 포기하고 수동으로 분석', score: 3 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '외부 AI 서비스에 데이터를 보낼 때는 반드시 개인 식별 정보를 익명화해야 합니다.',
  },
  {
    id: 'ethics-4',
    domain: 'ethics',
    type: 'multiple_choice',
    difficulty: 2,
    question: 'AI가 생성한 코드를 프로덕션에 사용할 때 가장 중요한 고려사항은?',
    options: [
      { text: '보안 취약점 검토 + 라이선스 확인 + 코드 리뷰', score: 10 },
      { text: 'AI가 생성했으니 버그가 없을 것이라 신뢰', score: 1 },
      { text: '단위 테스트만 통과하면 OK', score: 5 },
      { text: 'AI 생성 코드는 절대 프로덕션에 사용하면 안 됨', score: 2 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'AI 생성 코드도 보안 취약점, 라이선스 문제, 논리 오류가 있을 수 있으므로 철저한 검토가 필요합니다.',
  },
  {
    id: 'ethics-5',
    domain: 'ethics',
    type: 'scenario',
    difficulty: 3,
    question: 'AI 챗봇이 의료 상담에서 잘못된 정보를 제공하여 환자가 위험에 처할 뻔했습니다. 가장 근본적인 해결책은?',
    scenario: '회사의 의료 AI 챗봇이 "두통이 있으면 아스피린을 3배 복용하라"고 답변했습니다.',
    options: [
      { text: '의료 전문가 검수 체계 구축 + AI 응답에 "전문가 상담 권장" 면책 고지 + 위험 답변 필터링', score: 10 },
      { text: '프롬프트를 더 정교하게 수정', score: 4 },
      { text: '해당 질문 유형을 차단', score: 5 },
      { text: '의료 AI 챗봇 서비스를 즉시 중단', score: 3 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '고위험 영역에서의 AI는 전문가 검수, 면책 고지, 안전장치를 반드시 갖춰야 합니다.',
  },
  {
    id: 'ethics-6',
    domain: 'ethics',
    type: 'scenario',
    difficulty: 1,
    question: '회사 내부 사업계획서를 ChatGPT 무료 버전에 붙여넣어 요약을 받으려 합니다. 가장 적절한 판단은?',
    scenario: '아직 외부에 공개되지 않은 내년도 신사업 전략 자료입니다.',
    options: [
      { text: '대외비 자료는 학습/저장 정책이 명확한 엔터프라이즈 플랜이나 온프레미스 모델만 사용해야 함', score: 10 },
      { text: '무료 버전이어도 대화 내용은 저장되지 않으니 괜찮음', score: 2 },
      { text: '요약만 받으면 원본은 노출되지 않으므로 괜찮음', score: 3 },
      { text: '민감한 부분만 지우고 나머지를 붙여넣기', score: 5 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '무료 버전은 입력 데이터가 모델 학습에 사용될 수 있으며, 대외비 자료는 데이터 보호 정책이 보장된 환경에서만 처리해야 합니다.',
  },
  {
    id: 'ethics-7',
    domain: 'ethics',
    type: 'multiple_choice',
    difficulty: 2,
    question: 'AI 이미지 생성 도구로 만든 이미지를 상업적으로 사용하려 합니다. 저작권 관점에서 가장 적절한 판단은?',
    options: [
      { text: '생성 AI 이미지의 저작권은 확립되지 않았으며, 서비스 약관 확인 + 학습 데이터의 기존 저작물 유사성 검토 필요', score: 10 },
      { text: 'AI가 만든 것이므로 저작권이 없어 자유롭게 사용 가능', score: 3 },
      { text: 'AI 이미지는 무조건 상업적 사용이 불법', score: 2 },
      { text: '출처를 "AI 생성"으로 표기하면 문제없음', score: 4 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'AI 생성 이미지의 저작권은 아직 법적으로 확립되지 않았으며, 학습 데이터에 포함된 기존 저작물과의 유사성 문제도 검토해야 합니다.',
  },
  {
    id: 'ethics-8',
    domain: 'ethics',
    type: 'scenario',
    difficulty: 2,
    question: '한국 개인정보보호법(PIPA) 하에서 고객 데이터를 해외 AI 서비스에 보내려 합니다. 가장 적절한 조치는?',
    scenario: '고객 상담 내역을 OpenAI API로 분석하여 인사이트를 도출하려 하며, 데이터에 고객 이름과 연락처가 포함되어 있습니다.',
    options: [
      { text: '국외 이전 동의 확보 + 가명처리 + 계약으로 보호조치 확보', score: 10 },
      { text: 'OpenAI가 글로벌 기업이므로 별도 조치 없이 전송 가능', score: 1 },
      { text: '개인정보 부분만 삭제하고 전송하면 충분', score: 5 },
      { text: '한국 서버를 경유하면 국외 이전에 해당하지 않음', score: 2 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '개인정보보호법상 국외 이전 시 정보주체 동의, 가명/익명 처리, 수탁자와의 보호조치 계약이 필요합니다.',
  },
  {
    id: 'ethics-9',
    domain: 'ethics',
    type: 'multiple_choice',
    difficulty: 3,
    question: '기업이 AI 의사결정 시스템을 도입할 때, 거버넌스(추적·감사·책임 소재) 관점에서 반드시 갖춰야 할 체계는?',
    options: [
      { text: '결정 로그 기록 + 정기 감사 + 책임자 지정 + 이의제기 채널 마련', score: 10 },
      { text: 'AI 정확도가 90% 이상이면 별도 감사 불필요', score: 2 },
      { text: 'AI 벤더가 제공하는 대시보드로 모니터링하면 충분', score: 4 },
      { text: '분기별 성과 보고서만 작성', score: 3 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'AI 거버넌스는 의사결정의 추적 가능성, 정기적 감사, 명확한 책임 소재, 영향받는 당사자의 이의제기 수단을 모두 포함해야 합니다.',
  },
  {
    id: 'ethics-10',
    domain: 'ethics',
    type: 'scenario',
    difficulty: 3,
    question: 'AI 면접 도구가 특정 연령대에 불리한 결과를 보이는 것을 발견했습니다. 가장 적절한 대응은?',
    scenario: '데이터 분석 결과, 40대 이상 지원자의 AI 면접 통과율이 20대 대비 현저히 낮다는 것이 확인되었습니다.',
    options: [
      { text: '즉시 사용 중단 + 편향 원인 분석 + 영향받은 지원자 재평가 + 개선 후 재도입', score: 10 },
      { text: '40대 이상 점수에 보정 가산점 부여', score: 4 },
      { text: '연령 데이터를 입력에서 제거하고 계속 사용', score: 5 },
      { text: '통계적으로 유의미한지 추가 분석 후 판단', score: 3 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '편향이 확인된 AI 도구는 즉시 중단하고, 원인 분석 → 영향받은 대상 구제 → 개선 후 재도입의 순서로 대응해야 합니다.',
  },
];

// ─── 개념 이해 (Concept) ────────────────────────────
export const CONCEPT_QUESTIONS: AQQuestion[] = [
  {
    id: 'concept-1',
    domain: 'concept',
    type: 'multiple_choice',
    difficulty: 1,
    question: 'LLM(대규모 언어 모델)이 때때로 "할루시네이션"(사실이 아닌 내용을 생성)을 일으키는 근본적 이유는?',
    options: [
      { text: 'LLM은 확률적으로 다음 토큰을 예측하는 모델이라 사실을 "알고" 있는 것이 아니라 그럴듯한 텍스트를 생성하기 때문', score: 10 },
      { text: '학습 데이터에 오류가 많아서', score: 4 },
      { text: '인터넷 연결이 불안정해서 정보를 잘못 가져오기 때문', score: 1 },
      { text: '모델의 메모리 용량이 부족해서', score: 2 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'LLM은 사실 데이터베이스가 아닌 확률적 텍스트 생성 모델이므로, 그럴듯하지만 사실이 아닌 내용을 생성할 수 있습니다.',
  },
  {
    id: 'concept-2',
    domain: 'concept',
    type: 'multiple_choice',
    difficulty: 1,
    question: '"파인튜닝(Fine-tuning)"과 "프롬프트 엔지니어링"의 핵심 차이는?',
    options: [
      { text: '파인튜닝은 모델 자체를 추가 데이터로 재학습시키는 것, 프롬프트 엔지니어링은 입력을 정교하게 설계하여 원하는 출력을 이끌어내는 것', score: 10 },
      { text: '파인튜닝은 무료이고 프롬프트 엔지니어링은 유료', score: 1 },
      { text: '프롬프트 엔지니어링이 파인튜닝보다 항상 더 좋은 결과를 냄', score: 2 },
      { text: '파인튜닝은 텍스트에만 적용되고 프롬프트 엔지니어링은 이미지에만 적용됨', score: 0 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '파인튜닝은 모델 가중치를 변경하는 학습 과정이고, 프롬프트 엔지니어링은 모델을 변경하지 않고 입력만 최적화하는 기법입니다.',
  },
  {
    id: 'concept-3',
    domain: 'concept',
    type: 'multiple_choice',
    difficulty: 2,
    question: 'AI에서 "토큰(Token)"이란 무엇이며, 왜 중요한가요?',
    options: [
      { text: '모델이 텍스트를 처리하는 기본 단위(단어, 서브워드, 문자)로, 비용과 컨텍스트 길이에 직접 영향', score: 10 },
      { text: 'AI 서비스를 이용할 때 필요한 디지털 화폐', score: 1 },
      { text: '모델의 정확도를 측정하는 단위', score: 2 },
      { text: 'AI가 이해할 수 있는 프로그래밍 언어의 명령어', score: 3 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '토큰은 LLM이 텍스트를 처리하는 최소 단위로, API 비용 계산과 컨텍스트 윈도우 크기에 직접 영향을 미칩니다.',
  },
  {
    id: 'concept-4',
    domain: 'concept',
    type: 'multiple_choice',
    difficulty: 2,
    question: '"RAG(Retrieval-Augmented Generation)"가 필요한 상황은?',
    options: [
      { text: '모델이 학습하지 않은 최신/내부 데이터를 활용해야 할 때, 외부 지식을 검색해서 프롬프트에 넣어주는 방식', score: 10 },
      { text: 'AI 모델의 응답 속도를 높이고 싶을 때', score: 2 },
      { text: '이미지를 생성해야 할 때', score: 0 },
      { text: '여러 AI 모델을 동시에 실행해야 할 때', score: 3 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'RAG는 모델의 학습 데이터에 없는 최신 정보나 내부 문서를 검색하여 컨텍스트로 제공함으로써 정확한 답변을 생성하는 기법입니다.',
  },
  {
    id: 'concept-5',
    domain: 'concept',
    type: 'multiple_choice',
    difficulty: 3,
    question: 'GPT, Claude 같은 LLM의 "컨텍스트 윈도우" 한계가 실무에 미치는 영향으로 가장 정확한 설명은?',
    options: [
      { text: '한 번에 처리할 수 있는 텍스트 양이 제한되어 큰 문서는 분할 처리 필요, 대화가 길어지면 앞 내용을 "잊음"', score: 10 },
      { text: '컨텍스트 윈도우가 크면 항상 더 좋은 답변을 생성', score: 3 },
      { text: '컨텍스트 윈도우는 동시 접속자 수를 의미', score: 0 },
      { text: '컨텍스트 윈도우는 AI가 학습한 데이터의 총량', score: 2 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '컨텍스트 윈도우는 한 번에 처리 가능한 입출력 토큰의 총량이며, 이를 초과하면 정보가 유실되어 문서 분할이나 요약 전략이 필요합니다.',
  },
  {
    id: 'concept-6',
    domain: 'concept',
    type: 'multiple_choice',
    difficulty: 1,
    question: '한국어가 영어보다 LLM에서 토큰을 더 많이 소비하는 이유는?',
    options: [
      { text: '대부분의 LLM 토크나이저가 영어 중심으로 설계되어 한국어 한 글자가 여러 토큰으로 분해됨', score: 10 },
      { text: '한국어가 영어보다 문법이 복잡하기 때문', score: 4 },
      { text: '한글 유니코드가 영어 ASCII보다 용량이 크기 때문', score: 5 },
      { text: '한국어 데이터가 학습에 아예 포함되지 않아서', score: 1 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '영어 중심 토크나이저에서 한국어는 한 음절이 2~3개 토큰으로 분해되어 비용이 증가하고 가용 컨텍스트가 줄어듭니다.',
  },
  {
    id: 'concept-7',
    domain: 'concept',
    type: 'multiple_choice',
    difficulty: 2,
    question: '"챗봇"과 "AI 에이전트"의 핵심적인 차이는?',
    options: [
      { text: '챗봇은 대화 인터페이스로 질문에 응답, 에이전트는 목표를 받으면 도구를 활용하며 자율적으로 여러 단계를 계획·실행', score: 10 },
      { text: '챗봇은 텍스트만, 에이전트는 이미지도 처리 가능', score: 2 },
      { text: '에이전트는 챗봇보다 항상 더 비싸고 느림', score: 3 },
      { text: '챗봇은 클라우드 기반, 에이전트는 로컬에서만 동작', score: 1 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'AI 에이전트는 목표를 설정하면 자율적으로 계획을 세우고, 외부 도구를 활용하여 다단계 작업을 수행하는 것이 챗봇과의 핵심 차이입니다.',
  },
  {
    id: 'concept-8',
    domain: 'concept',
    type: 'multiple_choice',
    difficulty: 2,
    question: '"임베딩(Embedding)"이란 무엇인가요?',
    options: [
      { text: '텍스트를 수치 벡터로 변환하여 의미적 유사도를 계산할 수 있게 하는 기술 (검색, 추천, 분류에 활용)', score: 10 },
      { text: 'AI 모델을 웹사이트에 삽입하는 기술', score: 2 },
      { text: '이미지 안에 텍스트를 숨기는 워터마킹 기술', score: 1 },
      { text: 'AI가 학습하는 데이터를 압축하는 방법', score: 4 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: '임베딩은 텍스트를 고차원 벡터로 변환하여 의미적 유사도 비교를 가능하게 하며, 시맨틱 검색, 추천 시스템, 분류 등에 활용됩니다.',
  },
  {
    id: 'concept-9',
    domain: 'concept',
    type: 'multiple_choice',
    difficulty: 3,
    question: 'LLM이 "확신 있게 틀리는" 현상이 발생하는 근본 원인과 대응 방법은?',
    options: [
      { text: 'LLM은 정답 확률이 아닌 텍스트 유창성을 최적화하므로 확신도와 정확도가 비례하지 않음 → 중요 사실은 반드시 외부 소스로 검증', score: 10 },
      { text: '모델이 오래되어 최신 정보가 없기 때문 → 최신 모델로 교체하면 해결', score: 4 },
      { text: 'AI가 의도적으로 거짓말하기 때문 → 사용을 중단해야 함', score: 1 },
      { text: '프롬프트가 잘못되어서 → 프롬프트를 수정하면 해결', score: 5 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'LLM은 텍스트의 유창성과 일관성을 최적화하기 때문에 자신감 있는 어조와 사실의 정확도가 반드시 일치하지 않습니다. 중요 정보는 외부 검증이 필수입니다.',
  },
  {
    id: 'concept-10',
    domain: 'concept',
    type: 'multiple_choice',
    difficulty: 3,
    question: 'LLM에서 temperature와 top_p 파라미터의 역할과 "비결정성"에 대한 설명으로 가장 정확한 것은?',
    options: [
      { text: 'temperature는 출력의 무작위성을 조절(높을수록 창의적/위험), top_p는 누적확률 기반 필터링. 같은 프롬프트도 다른 결과가 나올 수 있는 것은 이 파라미터 때문', score: 10 },
      { text: 'temperature는 AI의 처리 속도, top_p는 정확도를 조절하는 파라미터', score: 2 },
      { text: '두 파라미터 모두 모델의 학습률을 조절하는 하이퍼파라미터', score: 1 },
      { text: 'temperature를 0으로 설정하면 항상 완벽하게 동일한 결과가 보장됨', score: 4 },
    ],
    correctIndex: 0,
    points: 10,
    explanation: 'temperature는 확률 분포의 날카로움을, top_p는 후보 토큰의 누적확률 범위를 조절합니다. 이 파라미터들이 LLM 출력의 비결정성을 만드는 핵심 요인입니다.',
  },
];

// ─── 전체 문제 뱅크 ─────────────────────────────────
export const ALL_AQ_QUESTIONS: AQQuestion[] = [
  ...TOOL_QUESTIONS,
  ...ETHICS_QUESTIONS,
  ...CONCEPT_QUESTIONS,
];